using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using XmlMiddleware.Application.Models;

namespace XmlMiddleware.Infrastructure.FileGeneration;

public class PdfGenerator : IGenerator
{
    public MemoryStream Generate(
        List<CanonicalOrderModel> orders)
    {
        QuestPDF.Settings.License =
            LicenseType.Community;

        var stream = new MemoryStream();

        QuestPDF.Fluent.Document
            .Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);

                    page.Header().Column(header =>
                    {
                        header.Item()
                            .Text("ORDER REPORT")
                            .FontSize(22)
                            .Bold();

                        header.Item()
                            .Text(
                                $"Generated On : {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");

                        header.Item()
                            .Text(
                                $"Total Orders : {orders.Count}");
                    });

                    page.Content().PaddingVertical(10)
                        .Column(column =>
                        {
                            foreach (var order in orders)
                            {
                                column.Item()
                                    .Border(1)
                                    .Padding(10)
                                    .Column(item =>
                                    {
                                        item.Item()
                                            .Text("Order Information")
                                            .FontSize(14)
                                            .Bold();

                                        item.Item()
                                            .PaddingTop(5);

                                        item.Item()
                                            .Text($"Order Id : {order.OrderId}");

                                        item.Item()
                                            .Text($"Order Date : {order.OrderDate:yyyy-MM-dd}");

                                        item.Item()
                                            .PaddingTop(5);

                                        item.Item()
                                            .Text($"Customer Id : {order.CustomerId}");

                                        item.Item()
                                            .Text($"Customer Name : {order.FirstName} {order.LastName}");

                                        item.Item()
                                            .Text($"Email : {order.Email}");

                                        item.Item()
                                            .PaddingTop(5);

                                        item.Item()
                                            .Text($"Address : {order.AddressLine1}");

                                        item.Item()
                                            .Text($"City : {order.City}");

                                        item.Item()
                                            .Text($"Post Code : {order.PostCode}");

                                        item.Item()
                                            .Text($"Country : {order.Country}");

                                        item.Item()
                                            .PaddingTop(5);

                                        item.Item()
                                            .Text($"Product Code : {order.ProductCode}");

                                        item.Item()
                                            .Text($"Product Name : {order.ProductName}");

                                        item.Item()
                                            .Text($"Quantity : {order.Quantity}");

                                        item.Item()
                                            .Text($"Unit Price : {order.UnitPrice:F2}");

                                        item.Item()
                                            .Text(
                                                $"Order Value : {(order.Quantity * order.UnitPrice):F2}");
                                    });

                                column.Item()
                                    .PaddingBottom(10);
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated By XML Middleware System");
                        });
                });
            })
            .GeneratePdf(stream);

        stream.Position = 0;

        return stream;
    }
}