// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XmlMiddleware.Persistence.Context;

#nullable disable

namespace XmlMiddleware.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910113538_RevertFileNameColumns")]
    partial class RevertFileNameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.OutputFile", b =>
                {
                    b.Property<long>("OutputFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OutputFileId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OutputBlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OutputType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OutputFileId");

                    b.HasIndex("BatchId", "OutputType")
                        .IsUnique();

                    b.ToTable("OutputFiles");
                });

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.ProcessingBatch", b =>
                {
                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BatchId"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LeaseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ProcessingEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("FileHash");

                    b.HasIndex("Status");

                    b.ToTable("ProcessingBatches");
                });

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.ProcessingEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("OutputFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex("OutputFileId");

                    b.ToTable("ProcessingEvents");
                });

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.OutputFile", b =>
                {
                    b.HasOne("XmlMiddleware.Domain.Entities.ProcessingBatch", "ProcessingBatch")
                        .WithMany("OutputFiles")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingBatch");
                });

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.ProcessingEvent", b =>
                {
                    b.HasOne("XmlMiddleware.Domain.Entities.ProcessingBatch", "ProcessingBatch")
                        .WithMany("ProcessingEvents")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlMiddleware.Domain.Entities.OutputFile", "OutputFile")
                        .WithMany()
                        .HasForeignKey("OutputFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OutputFile");

                    b.Navigation("ProcessingBatch");
                });

            modelBuilder.Entity("XmlMiddleware.Domain.Entities.ProcessingBatch", b =>
                {
                    b.Navigation("OutputFiles");

                    b.Navigation("ProcessingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
