<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="QuestPDF" Version="2026.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XmlMiddleware.Application\XmlMiddleware.Application.csproj" />
    <ProjectReference Include="..\XmlMiddleware.Domain\XmlMiddleware.Domain.csproj" />
    <ProjectReference Include="..\XmlMiddleware.Persistence\XmlMiddleware.Persistence.csproj" />
  </ItemGroup>

</Project>
